name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  contract-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Resolve dependencies
      run: npm install

    - name: Run tests
      run: npx hardhat test
